In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
np1=np.array([1,2,3,4])
np1

array([1, 2, 3, 4])

In [15]:
np2=np.array([20,30,40])
np2
type(np2)

numpy.ndarray

In [4]:
np3=np.array([[1,2,3],[4,5,6],[7,8,9]])
np3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.empty(3)

array([1., 1., 1.])

In [14]:
np.arange(2,17,3)

array([ 2,  5,  8, 11, 14])

In [16]:
arr=([8,4,9,7])
np.sort(arr)

array([4, 7, 8, 9])

In [18]:
arr1=([1,2,3,])
arr2=([4,5,6])
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [33]:
arr1=([4,1,3,])
arr5=([8,5,2])
np.sort((arr1,arr5))

array([[1, 3, 4],
       [2, 5, 8]])

In [22]:
arr1=([[1,2,3,],[7,8,9]])
arr2=([[4,5,6]])
np.concatenate((arr1,arr2),axis=0) #axis used for conversion

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [23]:
arr1=([[[4,5],[6,7]]])
arr2=([[[1,2],[3,4]]])
arr3=([[[4,5],[3,5]]])
np.concatenate((arr1,arr2,arr3),axis=0)

array([[[4, 5],
        [6, 7]],

       [[1, 2],
        [3, 4]],

       [[4, 5],
        [3, 5]]])

In [39]:
arr1.shape

AttributeError: 'list' object has no attribute 'shape'

In [2]:
arr6=np.array([1,2,3,4,5,6])  #creating numpy array
np.save("filename",arr6)   #here we save the array

In [41]:
arr7=np.load("filename.npy")   #here we load the array 
arr7

array([1, 2, 3, 4, 5, 6])

In [ ]:
#importing and Exporting a csv(comma separated value)
#install pandas list-- pip install pandas
#import pandas as pd
#create np array into pd.DataFrame
#save it as csv--- pd.to_csv("filename.csv")
#read csv into a variable -- .read_csv(" ")
#print

In [42]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [43]:
import pandas as pd

In [48]:
arr10=np.array([[0.111],[0.222],[0.333],[0.444]])

In [49]:
myvar=pd.DataFrame(arr10)
myvar

In [51]:
myvar.to_csv("pd.csv")

In [55]:
data=pd.read_csv("pd.csv")
data

Unnamed: 0      0
0           0  0.111
1           1  0.222
2           2  0.333
3           3  0.444